Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace RegistrationForm.DataModel

    Partial Public Class Employee
        Public Property ID() As Integer
        Public Property FirstName() As String
        Public Property LastName() As String
        Public Property Email() As String
        Public Property Password() As String
        Public Property Birthday() As Date
        Public Property Gender() As Integer
    End Class
End Namespace
